### ISSUE TITLE
生成pdf文字不可搜索

### ISSUE THREAD

**Issue by ggplot-2** [huiselilun/USTBThesis#5]
是否考虑用XeTex？

**Comment by Jeff-Hugh** [comment]
全部文件转换为UTF-8格式（已更新），现在可以使用XeLaTeX进行编译。生成的pdf也可以进行文字搜索。

**Comment by ggplot-2** [comment]
从某种程度上，我后来一直想将这个移植到Texmacs上直接用可视化界面，用起来可能会更简单些。

**Comment by Jeff-Hugh** [comment]
我没有使用过TeXmacs，抱歉。
