### ISSUE TITLE
关于conver中的空白页

### ISSUE THREAD

**Issue by ChaoFan96** [huiselilun/USTBThesis#7]
感谢您的工作！请问如何去掉Cover中多余的空白页？我尝试ThesisCover中注释\newpage无果。

**Comment by Jeff-Hugh** [comment]
空白页的出现是由book的文档格式确定的，因为有正反页之分，所以在开启新的章节时，处于反面的没有内容的页面就会留白。
如果要删除的话，请你修改关于正反页的设置。
抱歉我没有时间和能力解决这个问题。

**Comment by ChaoFan96** [comment]
感谢你的回复，问题已经解决；
我仔细看了模板，Conver中确实该留空白页，此处有叨扰，请见谅。
此外我针对一些问题提供了解决方案，拱你参考：
1、chapter末的多余空白页消除，可尝试用\let\cleardoublepage\clearpage；
2、英文黑体，可尝试$\bm{{\rm xxx}}$替代，尽管与理想黑体有区别，但将就着用；
3、“参考文献”几个字top边距过大，在目录下编辑bibspacing.sty文件：
\newdimen\bibindent
\setlength\bibindent{1.5em}
\newdimen\bibspacing
\setlength\bibspacing\z@
\renewenvironment{thebibliography}[1]{%
  \section*{\refname
        \@mkboth{\MakeUppercase\refname}{\MakeUppercase\refname}}%
      \list{\@biblabel{\@arabic\c@enumiv}}%
           {\settowidth\labelwidth{\@biblabel{#1}}%
            \leftmargin\labelwidth
            \advance\leftmargin\labelsep
            \itemsep\z@skip    % should this be commented out?
            \parsep\z@skip     % should this be commented out?
            \@openbib@code
            \usecounter{enumiv}%
            \let\p@enumiv\@empty
            \renewcommand\theenumiv{\@arabic\c@enumiv}}%
      \sloppy\clubpenalty4000\widowpenalty4000%
      \sfcode`\.\@m}
     {\def\@noitemerr
       {\@latex@warning{Empty `thebibliography' environment}}%
      \endlist}
在main.tex中\bibliography{ref}前添加：
\addcontentsline{toc}{chapter}{参考文献}  %在目录中添加“参考文献”的标记
\bibliographystyle{gbt7714-2005}
\renewcommand\refname{\centerline{参考文献}}
我这边试过是能解决这个问题的；
4、模板没有设置装订线预留的边距，将USTBThesis.cls文件中页边距设置一行中left参数设置为40mm.
发现了一个仍未解决的bug：
图表之后的文字会自动黑体，直到下一小结的标题之前，
原因没整明白，目前解决方案是把所有图表都放在标题之前，凑合着用。
请问你有解决思路吗？

**Comment by Jeff-Hugh** [comment]
感谢你提供的解决方案。此项目已经很久没有更新，而我也不再使用这个模板。你可以随意fork，或请求合并到这个分支，或自己发布都可以。Feel Free!
